### ISSUE TITLE
Jackal.js-protos error with babel.

### ISSUE THREAD

**Issue by whitebird1016** [JackalLabs/jackal.js-protos#14]
./node_modules/jackal.js-protos/dist/index.es.js 634:26
Module parse failed: Unexpected token (634:26)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   fromPartial(e) {
|     const r = ci();
>     return r.key = e.key ?? new Uint8Array(), r.offset = e.offset ?? 0, r.limit = e.limit ?? 0, r.countTotal = e.countTotal ?? !1, r.reverse = e.reverse ?? !1, r;
|   }
| };

hello I tried to use jackal.js on my project but not working.
actually my project is using babel.js.
I asked about jackal.js to community and they said me jackal.js don't prefer babel.js .
so how can I fix it?

**Comment by karnthis** [comment]
Based on a quick Google of your error, it looks like Babel is expecting an older codebase. Please use the linked SO answer to update what JS versions are acceptable.

https://stackoverflow.com/a/71037227

**Comment by whitebird1016** [comment]
Thanks
